name: Python application

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
   - cron: "0 0 */1 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser
        pip install requests beautifulsoup4  # 추가된 부분: requests와 beautifulsoup4 설치
    - name: Run Update Python Script
      run: |
        python main.py
    - name: Update README.md file
      run: |
        git pull
        git add .
        git diff
        git config --local user.email "chweyunn@gmail.com"
        git config --local user.name "chweyun"
        git commit -m "Update README with latest blog posts"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
